In [1]:
! pip install --upgrade pip
! pip install --upgrade Pillow

Requirement already satisfied: pip in c:\users\zhang\anaconda3\lib\site-packages (23.3.1)
Collecting pip
  Downloading pip-24.0-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-24.0-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 2.1/2.1 MB 8.4 MB/s eta 0:00:00

ERROR: To modify pip, please run the following command:
C:\Users\zhang\anaconda3\python.exe -m pip install --upgrade pip

Requirement already satisfied: Pillow in c:\users\zhang\anaconda3\lib\site-packages (10.2.0)

In [2]:
"C:/Users/zhang/Documents/Python Scripts/Rorschach Images-20240208T201917Z-001/Rorschach Images/"
"C:/Users/zhang/Documents/GitHub/Lab-Excercises/Lab 2/Rorschach Images-20240208T201917Z-001/Rorschach Images/"

'C:/Users/zhang/Documents/Python Scripts/Rorschach Images-20240208T201917Z-001/Rorschach Images/'

In [3]:
from PIL import Image

In [4]:
import os
import random

In [5]:
def choose_image():
    file = random.choice(os.listdir(r"C:/Users/zhang/Documents/GitHub/Lab-Excercises/Lab 2/Rorschach Images-20240208T201917Z-001/Rorschach Images/"))
    image = Image.open(f"C:/Users/zhang/Documents/GitHub/Lab-Excercises/Lab 2/Rorschach Images-20240208T201917Z-001/Rorschach Images/{file}", "r")
    image.show()
    return file

choose_image()

'39.png'

In [6]:
import csv

In [7]:
csv_file = open("Rorschach_data.csv", "w", newline="", encoding="utf-8")
csv_writer = csv.writer(csv_file)
csv_writer.writerow(["Image", "Data"])

csv_file.close()

In [8]:
#reading csv
import pandas as pd
sheet=pd.read_csv("Rorschach_data.csv")
sheet

Empty DataFrame
Columns: [Image, Data]
Index: []

In [9]:
#Populates file with a row w/ data
class Rorschach_csv:
    def __init__(self,name):
        self.name=name
        csv_file = open(self.name+"_Rorschach_data.csv", "w", newline="", encoding="utf-8")
        csv_writer = csv.writer(csv_file)
        csv_writer.writerow(["Image", "Data"])
        csv_file.close()
    def rorschach_csv_filler(self,number_of_desired_entries):
        self.number_of_desired_entries=number_of_desired_entries
        for i in range(self.number_of_desired_entries):
            csv_file = open(self.name+"_Rorschach_data.csv", "a", newline="", encoding="utf-8")
            csv_writer = csv.writer(csv_file)
            image_name=choose_image()
            user_input=input("Briefly describe what you see in the image: ")
            csv_writer.writerow([image_name, user_input])
            csv_file.close()
            sheet=pd.read_csv(self.name+"_Rorschach_data.csv")
        return sheet

##

In [10]:
Kevin=Rorschach_csv("Kevin")
Kevin.rorschach_csv_filler(2)

Briefly describe what you see in the image: skull
Briefly describe what you see in the image: skull again

    Image         Data
0  99.png        skull
1  99.png  skull again

In [11]:
Kevin_but_again=Rorschach_csv("Kevin_but_again")
Kevin_but_again.rorschach_csv_filler(3)

Briefly describe what you see in the image: Flower
Briefly describe what you see in the image: Bug
Briefly describe what you see in the image: Two cleavers

    Image          Data
0  48.png        Flower
1  79.png           Bug
2   1.png  Two cleavers

In [12]:
Kevin_plays_it_again=Rorschach_csv("Kevin_plays_it_again")
Kevin_plays_it_again.rorschach_csv_filler(2)

Briefly describe what you see in the image: Skull
Briefly describe what you see in the image: Helmet

     Image    Data
0   32.png   Skull
1  100.png  Helmet

In [13]:
Nivek=Rorschach_csv("Nivek")
Nivek.rorschach_csv_filler(2)

Briefly describe what you see in the image: heart
Briefly describe what you see in the image: Idk

    Image   Data
0  10.png  heart
1  46.png    Idk

In [14]:
Zhang=Rorschach_csv("Zhang")
Zhang.rorschach_csv_filler(2)

Briefly describe what you see in the image: Big old face
Briefly describe what you see in the image: island

    Image          Data
0   4.png  Big old face
1  16.png        island